---

kind: pipeline
type: docker
name: testing-1

steps:

- name: print-env
  image: busybox:1
  when:
    event:
    - push
    - tag
  commands:
  - echo tag=${DRONE_TAG} branch=${DRONE_BRANCH} commit=${DRONE_COMMIT}
  - env

- name: checkout-submodules
  image: alpine/git:v2.30.1
  when:
    event:
    - push
    - tag
  commands:
  - ls -hal .
  # now submodule folders are empty
  - ls -hal more/hello-octapus/
  # now checkout submodule(s)
  - git submodule init
  - git submodule update --recursive
  - ls -hal more/hello-octapus/

---

# An example using Docker-in-Docker for testing
# see also: https://docs.drone.io/pipeline/docker/examples/services/docker_dind/

kind: pipeline
type: docker
name: testing-2

steps:
- name: nosetests-in-docker
  image: docker:19.03-dind
  when:
    event:
    - push
    - tag
  volumes:
  - name: docker_run
    path: /var/run
  environment:
    DOCKER_HOST: unix:///var/run/docker.sock
  commands:
  # wait for Docker service to be up
  - >-
    (t=0; T=5; while ! docker info -f '{{.ID}}' 2>/dev/null; do t=$(( t + 1 )); test ${t} -ne ${T}; sleep 1; done)
  - docker info
  # build the image for testing
  - docker build . -f testing.dockerfile -t hello-flask:${DRONE_COMMIT}-testing
  # run nosetests inside a testing container
  - docker run --rm -u 1000:1000 -v $PWD:/work -w /work/helloworld hello-flask:${DRONE_COMMIT}-testing nosetests -v
  - echo $${DRONE_COMMIT::10}

services:
- name: docker
  image: docker:19.03-dind
  privileged: true
  command:
  # optional: use a registry mirror to cache images from Docker Hub
  - --registry-mirror=http://registry-mirror:5000
  volumes:
  - name: docker_run
    path: /var/run

volumes:
- name: docker_run
  temp: {}


---

# An example using a Drone "docker" plugin (plugins/docker) for publishing an image to a registry

kind: pipeline
type: docker
name: publish

environment:
  TAG_1: 'gunicorn'

steps:

- name: prepare-tags-1
  image: busybox:1.32
  when:
    event:
    - tag
  commands:
  - echo -n "1,${DRONE_TAG},${DRONE_TAG}-$${TAG_1}" | tee .tags

- name: publish-image-1
  image: plugins/docker
  when:
    event:
    - tag
  settings:
    debug: true
    username: alexakis
    password:
      from_secret: docker_password
    repo: alexakis/hello-flask
    mirror: http://registry-mirror:5000
    build_args: &build_args
    - git_commit=${DRONE_COMMIT}

- name: prepare-tags-2
  image: busybox:1.32
  when:
    event:
    - tag
  commands:
  - echo -n "1,1-snapshot,${DRONE_TAG},${DRONE_TAG}-$${TAG_1}" | tee .tags

- name: publish-image-2
  image: plugins/docker
  when:
    event:
    - tag
  settings:
    debug: true
    username:
      from_secret: registry_username
    password:
      from_secret: registry_password
    repo: registry-dev-1-opertusmundi:30474/opertusmundi/api-gateway
    mirror: http://registry-mirror:5000
    registry: registry-dev-1-opertusmundi:30474
    build_args: *build_args

# https://docs.drone.io/pipeline/configuration/#graph-execution
depends_on:
- testing-1
- testing-2




