kind: pipeline
type: docker
name: default

steps:
- name: nosetests
  image: python:3.8-alpine 
  when:
    event:
    - push
    - tag
  environment:
    REGISTRY_PASSWORD:
      from_secret: registry_password
  commands:
  - env
  - cd helloworld && pip install -r requirements.txt -r requirements-testing.txt
  - cd helloworld && python setup.py nosetests --verbosity=2
  - echo tag=${DRONE_TAG} branch=${DRONE_BRANCH} commit=${DRONE_COMMIT}

