---

kind: pipeline
type: docker
name: testing-1

steps:
- name: nosetests
  image: python:3.8-alpine 
  when:
    event:
    - push
    - tag
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
    REGISTRY_PASSWORD:
      from_secret: registry_password
  commands:
  - echo tag=${DRONE_TAG} branch=${DRONE_BRANCH} commit=${DRONE_COMMIT}
  - env
  - ls -hal .
  - cd helloworld
  - pip install -r requirements.txt -r requirements-testing.txt
  - python setup.py nosetests --verbosity=2


---

# An example using Docker-in-Docker for testing
# see also: https://docs.drone.io/pipeline/docker/examples/services/docker_dind/

kind: pipeline
type: docker
name: testing-2

steps:
- name: nosetests-in-docker
  image: docker:19.03-dind
  when:
    event:
    - push
    - tag
  volumes:
  - name: docker_run
    path: /var/run
  environment:
    DOCKER_HOST: unix:///var/run/docker.sock
  commands:
  # wait for Docker service to be up
  - >-
    (t=0; T=5; while ! docker info -f '{{.ID}}' 2>/dev/null; do t=$(( t + 1 )); test ${t} -ne ${T}; sleep 1; done)
  - docker info
  # build the image for testing
  - docker build . -f testing.dockerfile -t hello-flask:${DRONE_COMMIT}-testing
  # run nosetests inside a testing container
  - docker run --rm -u 1000:1000 -v $PWD:/work -w /work/helloworld hello-flask:${DRONE_COMMIT}-testing nosetests -v

services:
- name: docker
  image: docker:19.03-dind
  privileged: true
  command:
  # optional: use a registry mirror to cache images from Docker Hub
  - --registry-mirror=http://registry-mirror:5000
  volumes:
  - name: docker_run
    path: /var/run

volumes:
- name: docker_run
  temp: {}
